export const siteConfig = {
  name: 'DevLog',
  tagline: 'A programmer\'s thoughts on code, tools & craft',
  description: 'Personal blog about software engineering, programming languages, and developer tools.',
  url: process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000',
  author: {
    name: 'Your Name',
    email: 'you@example.com',
    github: 'yourusername',
    twitter: '@yourhandle',
    bio: 'Software engineer who loves building things with code. Writing about what I learn along the way.',
  },
  postsPerPage: 10,
  accentColor: '#6366f1',
  giscus: {
    repo: (process.env.NEXT_PUBLIC_GISCUS_REPO || 'yourusername/blog-discussions') as `${string}/${string}`,
    repoId: process.env.NEXT_PUBLIC_GISCUS_REPO_ID || 'R_xxxxx',
    category: process.env.NEXT_PUBLIC_GISCUS_CATEGORY || 'Announcements',
    categoryId: process.env.NEXT_PUBLIC_GISCUS_CATEGORY_ID || 'DIC_xxxxx',
    mapping: 'pathname' as const,
    strict: '0',
    reactionsEnabled: '1',
    emitMetadata: '0',
    inputPosition: 'bottom' as const,
    lang: 'en',
  },
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Blog', href: '/blog' },
    { label: 'Categories', href: '/categories' },
    { label: 'Tags', href: '/tags' },
    { label: 'Archive', href: '/archive' },
    { label: 'About', href: '/about' },
  ],
}
